// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package db

import (
	"context"
	"database/sql"
)

const getAccountByLogin = `-- name: GetAccountByLogin :one
SELECT id, user_type, user_id, auth_type, auth_account, auth_secret, secret_salt, status
FROM t_account
WHERE auth_account = $1
  AND auth_type = $2
  AND is_deleted = 0
  AND status = 1
LIMIT 1
`

type GetAccountByLoginParams struct {
	AuthAccount string `json:"auth_account"`
	AuthType    string `json:"auth_type"`
}

type GetAccountByLoginRow struct {
	ID          string         `json:"id"`
	UserType    string         `json:"user_type"`
	UserID      string         `json:"user_id"`
	AuthType    string         `json:"auth_type"`
	AuthAccount string         `json:"auth_account"`
	AuthSecret  sql.NullString `json:"auth_secret"`
	SecretSalt  sql.NullString `json:"secret_salt"`
	Status      int32          `json:"status"`
}

// Fetch an active login record for password-style authentication.
func (q *Queries) GetAccountByLogin(ctx context.Context, arg GetAccountByLoginParams) (GetAccountByLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByLogin, arg.AuthAccount, arg.AuthType)
	var i GetAccountByLoginRow
	err := row.Scan(
		&i.ID,
		&i.UserType,
		&i.UserID,
		&i.AuthType,
		&i.AuthAccount,
		&i.AuthSecret,
		&i.SecretSalt,
		&i.Status,
	)
	return i, err
}
