// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: answer.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countAnswersByProject = `-- name: CountAnswersByProject :one
SELECT COUNT(*) FROM t_answer WHERE project_id = $1 AND is_deleted = 0
`

func (q *Queries) CountAnswersByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAnswersByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnswer = `-- name: CreateAnswer :exec
INSERT INTO t_answer (
    id, project_id, survey, answer, meta_info, attachment, temp_save,
    exam_info, exam_exercise_type, exam_score, repo_id,
    is_deleted, create_at, create_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    0, NOW(), $12
)
`

type CreateAnswerParams struct {
	ID               string          `json:"id"`
	ProjectID        string          `json:"project_id"`
	Survey           sql.NullString  `json:"survey"`
	Answer           sql.NullString  `json:"answer"`
	MetaInfo         sql.NullString  `json:"meta_info"`
	Attachment       sql.NullString  `json:"attachment"`
	TempSave         sql.NullInt32   `json:"temp_save"`
	ExamInfo         sql.NullString  `json:"exam_info"`
	ExamExerciseType sql.NullString  `json:"exam_exercise_type"`
	ExamScore        sql.NullFloat64 `json:"exam_score"`
	RepoID           sql.NullString  `json:"repo_id"`
	CreateBy         sql.NullString  `json:"create_by"`
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) error {
	_, err := q.db.ExecContext(ctx, createAnswer,
		arg.ID,
		arg.ProjectID,
		arg.Survey,
		arg.Answer,
		arg.MetaInfo,
		arg.Attachment,
		arg.TempSave,
		arg.ExamInfo,
		arg.ExamExerciseType,
		arg.ExamScore,
		arg.RepoID,
		arg.CreateBy,
	)
	return err
}

const getAnswerByID = `-- name: GetAnswerByID :one
SELECT id, project_id, survey, answer, attachment, meta_info, temp_save,
       exam_info, exam_exercise_type, exam_score, repo_id,
       create_at, create_by, update_at, update_by
FROM t_answer
WHERE id = $1 AND is_deleted = 0
`

type GetAnswerByIDRow struct {
	ID               string          `json:"id"`
	ProjectID        string          `json:"project_id"`
	Survey           sql.NullString  `json:"survey"`
	Answer           sql.NullString  `json:"answer"`
	Attachment       sql.NullString  `json:"attachment"`
	MetaInfo         sql.NullString  `json:"meta_info"`
	TempSave         sql.NullInt32   `json:"temp_save"`
	ExamInfo         sql.NullString  `json:"exam_info"`
	ExamExerciseType sql.NullString  `json:"exam_exercise_type"`
	ExamScore        sql.NullFloat64 `json:"exam_score"`
	RepoID           sql.NullString  `json:"repo_id"`
	CreateAt         time.Time       `json:"create_at"`
	CreateBy         sql.NullString  `json:"create_by"`
	UpdateAt         sql.NullTime    `json:"update_at"`
	UpdateBy         sql.NullString  `json:"update_by"`
}

func (q *Queries) GetAnswerByID(ctx context.Context, id string) (GetAnswerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAnswerByID, id)
	var i GetAnswerByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Survey,
		&i.Answer,
		&i.Attachment,
		&i.MetaInfo,
		&i.TempSave,
		&i.ExamInfo,
		&i.ExamExerciseType,
		&i.ExamScore,
		&i.RepoID,
		&i.CreateAt,
		&i.CreateBy,
		&i.UpdateAt,
		&i.UpdateBy,
	)
	return i, err
}

const listAnswersByProject = `-- name: ListAnswersByProject :many
SELECT id, project_id, temp_save, exam_score, exam_exercise_type,
       create_at, create_by, update_at
FROM t_answer
WHERE project_id = $1 AND is_deleted = 0
ORDER BY create_at DESC
LIMIT $2 OFFSET $3
`

type ListAnswersByProjectParams struct {
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListAnswersByProjectRow struct {
	ID               string          `json:"id"`
	ProjectID        string          `json:"project_id"`
	TempSave         sql.NullInt32   `json:"temp_save"`
	ExamScore        sql.NullFloat64 `json:"exam_score"`
	ExamExerciseType sql.NullString  `json:"exam_exercise_type"`
	CreateAt         time.Time       `json:"create_at"`
	CreateBy         sql.NullString  `json:"create_by"`
	UpdateAt         sql.NullTime    `json:"update_at"`
}

func (q *Queries) ListAnswersByProject(ctx context.Context, arg ListAnswersByProjectParams) ([]ListAnswersByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnswersByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnswersByProjectRow{}
	for rows.Next() {
		var i ListAnswersByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TempSave,
			&i.ExamScore,
			&i.ExamExerciseType,
			&i.CreateAt,
			&i.CreateBy,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAnswer = `-- name: SoftDeleteAnswer :exec
UPDATE t_answer SET is_deleted = 1, update_by = $1 WHERE id = $2 AND is_deleted = 0
`

type SoftDeleteAnswerParams struct {
	UpdateBy sql.NullString `json:"update_by"`
	ID       string         `json:"id"`
}

func (q *Queries) SoftDeleteAnswer(ctx context.Context, arg SoftDeleteAnswerParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteAnswer, arg.UpdateBy, arg.ID)
	return err
}

const updateAnswerInPlace = `-- name: UpdateAnswerInPlace :execrows
UPDATE t_answer SET
    survey     = COALESCE($3,     survey),
    answer     = COALESCE($4,     answer),
    attachment = COALESCE($5, attachment),
    meta_info  = COALESCE($6,  meta_info),
    temp_save  = COALESCE($7,  temp_save),
    exam_score = COALESCE($8, exam_score),
    update_by  = $1
WHERE id = $2 AND is_deleted = 0
`

type UpdateAnswerInPlaceParams struct {
	UpdateBy   sql.NullString  `json:"update_by"`
	ID         string          `json:"id"`
	Survey     sql.NullString  `json:"survey"`
	Answer     sql.NullString  `json:"answer"`
	Attachment sql.NullString  `json:"attachment"`
	MetaInfo   sql.NullString  `json:"meta_info"`
	TempSave   sql.NullInt32   `json:"temp_save"`
	ExamScore  sql.NullFloat64 `json:"exam_score"`
}

// Used by saveAnswer's resume flow: when the client returns a previously
// issued answerId, we patch the existing draft instead of creating a
// new row. Returns the number of rows touched so the service can fall
// back to insert if the id is stale (deleted or never existed).
func (q *Queries) UpdateAnswerInPlace(ctx context.Context, arg UpdateAnswerInPlaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAnswerInPlace,
		arg.UpdateBy,
		arg.ID,
		arg.Survey,
		arg.Answer,
		arg.Attachment,
		arg.MetaInfo,
		arg.TempSave,
		arg.ExamScore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
