// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countDashboards = `-- name: CountDashboards :one
SELECT COUNT(*) FROM t_dashboard
`

func (q *Queries) CountDashboards(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDashboards)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listDashboards = `-- name: ListDashboards :many
SELECT id, "key", "type", project_id, setting, create_at, update_at, create_by
FROM t_dashboard
ORDER BY create_at DESC
LIMIT $1 OFFSET $2
`

type ListDashboardsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListDashboardsRow struct {
	ID        string         `json:"id"`
	Key       string         `json:"key"`
	Type      sql.NullInt32  `json:"type"`
	ProjectID sql.NullString `json:"project_id"`
	Setting   sql.NullString `json:"setting"`
	CreateAt  time.Time      `json:"create_at"`
	UpdateAt  sql.NullTime   `json:"update_at"`
	CreateBy  sql.NullString `json:"create_by"`
}

func (q *Queries) ListDashboards(ctx context.Context, arg ListDashboardsParams) ([]ListDashboardsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDashboards, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardsRow{}
	for rows.Next() {
		var i ListDashboardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Type,
			&i.ProjectID,
			&i.Setting,
			&i.CreateAt,
			&i.UpdateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
