// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dept.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createDept = `-- name: CreateDept :exec
INSERT INTO t_dept (
    id, parent_id, name, short_name, code, manager_id, sort_code,
    property_json, status, remark, is_deleted, create_at, create_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 0, NOW(), $11)
`

type CreateDeptParams struct {
	ID           string         `json:"id"`
	ParentID     string         `json:"parent_id"`
	Name         sql.NullString `json:"name"`
	ShortName    string         `json:"short_name"`
	Code         sql.NullString `json:"code"`
	ManagerID    sql.NullString `json:"manager_id"`
	SortCode     sql.NullInt32  `json:"sort_code"`
	PropertyJson sql.NullString `json:"property_json"`
	Status       sql.NullString `json:"status"`
	Remark       sql.NullString `json:"remark"`
	CreateBy     sql.NullString `json:"create_by"`
}

func (q *Queries) CreateDept(ctx context.Context, arg CreateDeptParams) error {
	_, err := q.db.ExecContext(ctx, createDept,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.ShortName,
		arg.Code,
		arg.ManagerID,
		arg.SortCode,
		arg.PropertyJson,
		arg.Status,
		arg.Remark,
		arg.CreateBy,
	)
	return err
}

const getDeptByID = `-- name: GetDeptByID :one
SELECT id, parent_id, name, short_name, code, manager_id, sort_code,
       property_json, status, remark, create_at, update_at, create_by, update_by
FROM t_dept WHERE id = $1 AND is_deleted = 0
`

type GetDeptByIDRow struct {
	ID           string         `json:"id"`
	ParentID     string         `json:"parent_id"`
	Name         sql.NullString `json:"name"`
	ShortName    string         `json:"short_name"`
	Code         sql.NullString `json:"code"`
	ManagerID    sql.NullString `json:"manager_id"`
	SortCode     sql.NullInt32  `json:"sort_code"`
	PropertyJson sql.NullString `json:"property_json"`
	Status       sql.NullString `json:"status"`
	Remark       sql.NullString `json:"remark"`
	CreateAt     time.Time      `json:"create_at"`
	UpdateAt     sql.NullTime   `json:"update_at"`
	CreateBy     sql.NullString `json:"create_by"`
	UpdateBy     sql.NullString `json:"update_by"`
}

func (q *Queries) GetDeptByID(ctx context.Context, id string) (GetDeptByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDeptByID, id)
	var i GetDeptByIDRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.ManagerID,
		&i.SortCode,
		&i.PropertyJson,
		&i.Status,
		&i.Remark,
		&i.CreateAt,
		&i.UpdateAt,
		&i.CreateBy,
		&i.UpdateBy,
	)
	return i, err
}

const listDepts = `-- name: ListDepts :many
SELECT id, parent_id, name, short_name, code, manager_id, sort_code,
       property_json, status, remark, create_at, update_at, create_by
FROM t_dept WHERE is_deleted = 0
ORDER BY COALESCE(sort_code, 0) ASC, create_at ASC
`

type ListDeptsRow struct {
	ID           string         `json:"id"`
	ParentID     string         `json:"parent_id"`
	Name         sql.NullString `json:"name"`
	ShortName    string         `json:"short_name"`
	Code         sql.NullString `json:"code"`
	ManagerID    sql.NullString `json:"manager_id"`
	SortCode     sql.NullInt32  `json:"sort_code"`
	PropertyJson sql.NullString `json:"property_json"`
	Status       sql.NullString `json:"status"`
	Remark       sql.NullString `json:"remark"`
	CreateAt     time.Time      `json:"create_at"`
	UpdateAt     sql.NullTime   `json:"update_at"`
	CreateBy     sql.NullString `json:"create_by"`
}

func (q *Queries) ListDepts(ctx context.Context) ([]ListDeptsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDepts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeptsRow{}
	for rows.Next() {
		var i ListDeptsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.ShortName,
			&i.Code,
			&i.ManagerID,
			&i.SortCode,
			&i.PropertyJson,
			&i.Status,
			&i.Remark,
			&i.CreateAt,
			&i.UpdateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDept = `-- name: SoftDeleteDept :exec
UPDATE t_dept SET is_deleted = 1, update_by = $1 WHERE id = $2 AND is_deleted = 0
`

type SoftDeleteDeptParams struct {
	UpdateBy sql.NullString `json:"update_by"`
	ID       string         `json:"id"`
}

func (q *Queries) SoftDeleteDept(ctx context.Context, arg SoftDeleteDeptParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteDept, arg.UpdateBy, arg.ID)
	return err
}

const updateDept = `-- name: UpdateDept :exec
UPDATE t_dept SET
    parent_id     = COALESCE($3,     parent_id),
    name          = COALESCE($4,          name),
    short_name    = COALESCE($5,    short_name),
    code          = COALESCE($6,          code),
    manager_id    = COALESCE($7,    manager_id),
    sort_code     = COALESCE($8,     sort_code),
    property_json = COALESCE($9, property_json),
    status        = COALESCE($10,        status),
    remark        = COALESCE($11,        remark),
    update_by     = $1
WHERE id = $2 AND is_deleted = 0
`

type UpdateDeptParams struct {
	UpdateBy     sql.NullString `json:"update_by"`
	ID           string         `json:"id"`
	ParentID     sql.NullString `json:"parent_id"`
	Name         sql.NullString `json:"name"`
	ShortName    sql.NullString `json:"short_name"`
	Code         sql.NullString `json:"code"`
	ManagerID    sql.NullString `json:"manager_id"`
	SortCode     sql.NullInt32  `json:"sort_code"`
	PropertyJson sql.NullString `json:"property_json"`
	Status       sql.NullString `json:"status"`
	Remark       sql.NullString `json:"remark"`
}

func (q *Queries) UpdateDept(ctx context.Context, arg UpdateDeptParams) error {
	_, err := q.db.ExecContext(ctx, updateDept,
		arg.UpdateBy,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.ShortName,
		arg.Code,
		arg.ManagerID,
		arg.SortCode,
		arg.PropertyJson,
		arg.Status,
		arg.Remark,
	)
	return err
}
