// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dict.sql

package db

import (
	"context"
	"database/sql"
)

const countDictItems = `-- name: CountDictItems :one
SELECT COUNT(*) FROM t_comm_dict_item
WHERE ($1::varchar IS NULL OR dict_code = $1)
  AND ($2::varchar IS NULL OR parent_item_value = $2)
  AND ($3::text IS NULL OR item_name ILIKE '%' || $3::text || '%')
`

type CountDictItemsParams struct {
	DictCode        sql.NullString `json:"dict_code"`
	ParentItemValue sql.NullString `json:"parent_item_value"`
	ItemName        sql.NullString `json:"item_name"`
}

func (q *Queries) CountDictItems(ctx context.Context, arg CountDictItemsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDictItems, arg.DictCode, arg.ParentItemValue, arg.ItemName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDicts = `-- name: CountDicts :one
SELECT COUNT(*) FROM t_comm_dict
WHERE ($1::text  IS NULL OR name ILIKE '%' || $1::text || '%')
  AND ($2::varchar IS NULL OR code = $2)
`

type CountDictsParams struct {
	Name sql.NullString `json:"name"`
	Code sql.NullString `json:"code"`
}

func (q *Queries) CountDicts(ctx context.Context, arg CountDictsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDicts, arg.Name, arg.Code)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDict = `-- name: CreateDict :exec
INSERT INTO t_comm_dict (id, code, name, remark, dict_type, create_at, create_by)
VALUES ($1, $2, $3, $4, $5, NOW(), $6)
`

type CreateDictParams struct {
	ID       string         `json:"id"`
	Code     sql.NullString `json:"code"`
	Name     sql.NullString `json:"name"`
	Remark   sql.NullString `json:"remark"`
	DictType sql.NullInt32  `json:"dict_type"`
	CreateBy sql.NullString `json:"create_by"`
}

func (q *Queries) CreateDict(ctx context.Context, arg CreateDictParams) error {
	_, err := q.db.ExecContext(ctx, createDict,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Remark,
		arg.DictType,
		arg.CreateBy,
	)
	return err
}

const createDictItem = `-- name: CreateDictItem :exec
INSERT INTO t_comm_dict_item (id, dict_code, item_name, item_value, item_order,
                              item_level, parent_item_value, create_at, create_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), $8)
`

type CreateDictItemParams struct {
	ID              string         `json:"id"`
	DictCode        sql.NullString `json:"dict_code"`
	ItemName        sql.NullString `json:"item_name"`
	ItemValue       string         `json:"item_value"`
	ItemOrder       sql.NullInt32  `json:"item_order"`
	ItemLevel       sql.NullInt32  `json:"item_level"`
	ParentItemValue sql.NullString `json:"parent_item_value"`
	CreateBy        sql.NullString `json:"create_by"`
}

func (q *Queries) CreateDictItem(ctx context.Context, arg CreateDictItemParams) error {
	_, err := q.db.ExecContext(ctx, createDictItem,
		arg.ID,
		arg.DictCode,
		arg.ItemName,
		arg.ItemValue,
		arg.ItemOrder,
		arg.ItemLevel,
		arg.ParentItemValue,
		arg.CreateBy,
	)
	return err
}

const deleteDict = `-- name: DeleteDict :exec
DELETE FROM t_comm_dict WHERE id = $1
`

func (q *Queries) DeleteDict(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDict, id)
	return err
}

const deleteDictItem = `-- name: DeleteDictItem :exec
DELETE FROM t_comm_dict_item WHERE id = $1
`

func (q *Queries) DeleteDictItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDictItem, id)
	return err
}

const deleteDictItemScoped = `-- name: DeleteDictItemScoped :execrows
DELETE FROM t_comm_dict_item
 WHERE id = $1 AND dict_code = $2
`

type DeleteDictItemScopedParams struct {
	ID       string         `json:"id"`
	DictCode sql.NullString `json:"dict_code"`
}

// Companion to UpdateDictItemScoped — atomic delete gated on parent
// dict code, returns affected row count.
func (q *Queries) DeleteDictItemScoped(ctx context.Context, arg DeleteDictItemScopedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDictItemScoped, arg.ID, arg.DictCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDictItemsByCode = `-- name: DeleteDictItemsByCode :exec
DELETE FROM t_comm_dict_item WHERE dict_code = $1
`

// Cascade helper: when an admin deletes a t_comm_dict row, drop its
// items too.
func (q *Queries) DeleteDictItemsByCode(ctx context.Context, dictCode sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteDictItemsByCode, dictCode)
	return err
}

const getDictByID = `-- name: GetDictByID :one
SELECT id, code, name, remark, dict_type, create_at, update_at, create_by, update_by
FROM t_comm_dict WHERE id = $1
`

type GetDictByIDRow struct {
	ID       string         `json:"id"`
	Code     sql.NullString `json:"code"`
	Name     sql.NullString `json:"name"`
	Remark   sql.NullString `json:"remark"`
	DictType sql.NullInt32  `json:"dict_type"`
	CreateAt sql.NullTime   `json:"create_at"`
	UpdateAt sql.NullTime   `json:"update_at"`
	CreateBy sql.NullString `json:"create_by"`
	UpdateBy sql.NullString `json:"update_by"`
}

func (q *Queries) GetDictByID(ctx context.Context, id string) (GetDictByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDictByID, id)
	var i GetDictByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Remark,
		&i.DictType,
		&i.CreateAt,
		&i.UpdateAt,
		&i.CreateBy,
		&i.UpdateBy,
	)
	return i, err
}

const listDictItems = `-- name: ListDictItems :many

SELECT id, dict_code, item_name, item_value, item_order, item_level,
       parent_item_value, create_at, update_at, create_by
FROM t_comm_dict_item
WHERE ($1::varchar IS NULL OR dict_code = $1)
  AND ($2::varchar IS NULL OR parent_item_value = $2)
  AND ($3::text IS NULL OR item_name ILIKE '%' || $3::text || '%')
ORDER BY COALESCE(item_order, 0) ASC, create_at ASC
LIMIT $5 OFFSET $4
`

type ListDictItemsParams struct {
	DictCode        sql.NullString `json:"dict_code"`
	ParentItemValue sql.NullString `json:"parent_item_value"`
	ItemName        sql.NullString `json:"item_name"`
	Off             int32          `json:"off"`
	Lim             int32          `json:"lim"`
}

type ListDictItemsRow struct {
	ID              string         `json:"id"`
	DictCode        sql.NullString `json:"dict_code"`
	ItemName        sql.NullString `json:"item_name"`
	ItemValue       string         `json:"item_value"`
	ItemOrder       sql.NullInt32  `json:"item_order"`
	ItemLevel       sql.NullInt32  `json:"item_level"`
	ParentItemValue sql.NullString `json:"parent_item_value"`
	CreateAt        sql.NullTime   `json:"create_at"`
	UpdateAt        sql.NullTime   `json:"update_at"`
	CreateBy        sql.NullString `json:"create_by"`
}

// ----- t_comm_dict_item -----
func (q *Queries) ListDictItems(ctx context.Context, arg ListDictItemsParams) ([]ListDictItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDictItems,
		arg.DictCode,
		arg.ParentItemValue,
		arg.ItemName,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDictItemsRow{}
	for rows.Next() {
		var i ListDictItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.DictCode,
			&i.ItemName,
			&i.ItemValue,
			&i.ItemOrder,
			&i.ItemLevel,
			&i.ParentItemValue,
			&i.CreateAt,
			&i.UpdateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDicts = `-- name: ListDicts :many

SELECT id, code, name, remark, dict_type, create_at, update_at, create_by
FROM t_comm_dict
WHERE ($1::text  IS NULL OR name ILIKE '%' || $1::text || '%')
  AND ($2::varchar IS NULL OR code = $2)
ORDER BY create_at DESC
LIMIT $4 OFFSET $3
`

type ListDictsParams struct {
	Name sql.NullString `json:"name"`
	Code sql.NullString `json:"code"`
	Off  int32          `json:"off"`
	Lim  int32          `json:"lim"`
}

type ListDictsRow struct {
	ID       string         `json:"id"`
	Code     sql.NullString `json:"code"`
	Name     sql.NullString `json:"name"`
	Remark   sql.NullString `json:"remark"`
	DictType sql.NullInt32  `json:"dict_type"`
	CreateAt sql.NullTime   `json:"create_at"`
	UpdateAt sql.NullTime   `json:"update_at"`
	CreateBy sql.NullString `json:"create_by"`
}

// ----- t_comm_dict -----
func (q *Queries) ListDicts(ctx context.Context, arg ListDictsParams) ([]ListDictsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDicts,
		arg.Name,
		arg.Code,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDictsRow{}
	for rows.Next() {
		var i ListDictsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Remark,
			&i.DictType,
			&i.CreateAt,
			&i.UpdateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDict = `-- name: UpdateDict :exec
UPDATE t_comm_dict SET
    code      = COALESCE($3,      code),
    name      = COALESCE($4,      name),
    remark    = COALESCE($5,    remark),
    dict_type = COALESCE($6, dict_type),
    update_by = $1
WHERE id = $2
`

type UpdateDictParams struct {
	UpdateBy sql.NullString `json:"update_by"`
	ID       string         `json:"id"`
	Code     sql.NullString `json:"code"`
	Name     sql.NullString `json:"name"`
	Remark   sql.NullString `json:"remark"`
	DictType sql.NullInt32  `json:"dict_type"`
}

func (q *Queries) UpdateDict(ctx context.Context, arg UpdateDictParams) error {
	_, err := q.db.ExecContext(ctx, updateDict,
		arg.UpdateBy,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Remark,
		arg.DictType,
	)
	return err
}

const updateDictItem = `-- name: UpdateDictItem :exec
UPDATE t_comm_dict_item SET
    dict_code         = COALESCE($3,         dict_code),
    item_name         = COALESCE($4,         item_name),
    item_value        = COALESCE($5,        item_value),
    item_order        = COALESCE($6,        item_order),
    item_level        = COALESCE($7,        item_level),
    parent_item_value = COALESCE($8, parent_item_value),
    update_by         = $1
WHERE id = $2
`

type UpdateDictItemParams struct {
	UpdateBy        sql.NullString `json:"update_by"`
	ID              string         `json:"id"`
	DictCode        sql.NullString `json:"dict_code"`
	ItemName        sql.NullString `json:"item_name"`
	ItemValue       sql.NullString `json:"item_value"`
	ItemOrder       sql.NullInt32  `json:"item_order"`
	ItemLevel       sql.NullInt32  `json:"item_level"`
	ParentItemValue sql.NullString `json:"parent_item_value"`
}

func (q *Queries) UpdateDictItem(ctx context.Context, arg UpdateDictItemParams) error {
	_, err := q.db.ExecContext(ctx, updateDictItem,
		arg.UpdateBy,
		arg.ID,
		arg.DictCode,
		arg.ItemName,
		arg.ItemValue,
		arg.ItemOrder,
		arg.ItemLevel,
		arg.ParentItemValue,
	)
	return err
}

const updateDictItemScoped = `-- name: UpdateDictItemScoped :execrows
UPDATE t_comm_dict_item SET
    item_name         = COALESCE($1,         item_name),
    item_value        = COALESCE($2,        item_value),
    item_order        = COALESCE($3,        item_order),
    item_level        = COALESCE($4,        item_level),
    parent_item_value = COALESCE($5, parent_item_value),
    update_by         = $6
WHERE id = $7 AND dict_code = $8
`

type UpdateDictItemScopedParams struct {
	ItemName        sql.NullString `json:"item_name"`
	ItemValue       sql.NullString `json:"item_value"`
	ItemOrder       sql.NullInt32  `json:"item_order"`
	ItemLevel       sql.NullInt32  `json:"item_level"`
	ParentItemValue sql.NullString `json:"parent_item_value"`
	UpdateBy        sql.NullString `json:"update_by"`
	ID              string         `json:"id"`
	DictCode        sql.NullString `json:"dict_code"`
}

// Atomic update predicated on the parent dict's code. Caller must
// treat a 0-rows return as "not yours" (403/404). Used by the
// console handler to close the time-of-check / time-of-use gap an
// earlier two-step "validate then mutate" implementation had.
func (q *Queries) UpdateDictItemScoped(ctx context.Context, arg UpdateDictItemScopedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDictItemScoped,
		arg.ItemName,
		arg.ItemValue,
		arg.ItemOrder,
		arg.ItemLevel,
		arg.ParentItemValue,
		arg.UpdateBy,
		arg.ID,
		arg.DictCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
