// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO t_file (
    id, original_name, file_name, file_path, thumb_file_path, storage_type, shared,
    is_deleted, create_at, create_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 0, NOW(), $8
)
`

type CreateFileParams struct {
	ID            string         `json:"id"`
	OriginalName  sql.NullString `json:"original_name"`
	FileName      sql.NullString `json:"file_name"`
	FilePath      sql.NullString `json:"file_path"`
	ThumbFilePath sql.NullString `json:"thumb_file_path"`
	StorageType   sql.NullInt32  `json:"storage_type"`
	Shared        sql.NullInt32  `json:"shared"`
	CreateBy      sql.NullString `json:"create_by"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.ExecContext(ctx, createFile,
		arg.ID,
		arg.OriginalName,
		arg.FileName,
		arg.FilePath,
		arg.ThumbFilePath,
		arg.StorageType,
		arg.Shared,
		arg.CreateBy,
	)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, original_name, file_name, file_path, thumb_file_path, storage_type, shared,
       create_at, create_by, update_at, update_by
FROM t_file WHERE id = $1 AND is_deleted = 0
`

type GetFileByIDRow struct {
	ID            string         `json:"id"`
	OriginalName  sql.NullString `json:"original_name"`
	FileName      sql.NullString `json:"file_name"`
	FilePath      sql.NullString `json:"file_path"`
	ThumbFilePath sql.NullString `json:"thumb_file_path"`
	StorageType   sql.NullInt32  `json:"storage_type"`
	Shared        sql.NullInt32  `json:"shared"`
	CreateAt      time.Time      `json:"create_at"`
	CreateBy      sql.NullString `json:"create_by"`
	UpdateAt      sql.NullTime   `json:"update_at"`
	UpdateBy      sql.NullString `json:"update_by"`
}

func (q *Queries) GetFileByID(ctx context.Context, id string) (GetFileByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i GetFileByIDRow
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.FileName,
		&i.FilePath,
		&i.ThumbFilePath,
		&i.StorageType,
		&i.Shared,
		&i.CreateAt,
		&i.CreateBy,
		&i.UpdateAt,
		&i.UpdateBy,
	)
	return i, err
}

const softDeleteFile = `-- name: SoftDeleteFile :exec
UPDATE t_file SET is_deleted = 1, update_by = $1 WHERE id = $2 AND is_deleted = 0
`

type SoftDeleteFileParams struct {
	UpdateBy sql.NullString `json:"update_by"`
	ID       string         `json:"id"`
}

func (q *Queries) SoftDeleteFile(ctx context.Context, arg SoftDeleteFileParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteFile, arg.UpdateBy, arg.ID)
	return err
}
