// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type TAccount struct {
	ID          string         `json:"id"`
	UserType    string         `json:"user_type"`
	UserID      string         `json:"user_id"`
	AuthType    string         `json:"auth_type"`
	AuthAccount string         `json:"auth_account"`
	AuthSecret  sql.NullString `json:"auth_secret"`
	SecretSalt  sql.NullString `json:"secret_salt"`
	Status      int32          `json:"status"`
	IsDeleted   int16          `json:"is_deleted"`
	CreateAt    time.Time      `json:"create_at"`
	CreateBy    sql.NullString `json:"create_by"`
	UpdateAt    sql.NullTime   `json:"update_at"`
	UpdateBy    sql.NullString `json:"update_by"`
}

type TAnswer struct {
	ID               string          `json:"id"`
	ProjectID        string          `json:"project_id"`
	TempAnswer       sql.NullString  `json:"temp_answer"`
	Survey           sql.NullString  `json:"survey"`
	Answer           sql.NullString  `json:"answer"`
	Attachment       sql.NullString  `json:"attachment"`
	MetaInfo         sql.NullString  `json:"meta_info"`
	TempSave         sql.NullInt32   `json:"temp_save"`
	ExamInfo         sql.NullString  `json:"exam_info"`
	ExamExerciseType sql.NullString  `json:"exam_exercise_type"`
	ExamScore        sql.NullFloat64 `json:"exam_score"`
	IsDeleted        int16           `json:"is_deleted"`
	CreateAt         time.Time       `json:"create_at"`
	CreateBy         sql.NullString  `json:"create_by"`
	UpdateAt         sql.NullTime    `json:"update_at"`
	UpdateBy         sql.NullString  `json:"update_by"`
	RepoID           sql.NullString  `json:"repo_id"`
}

type TCommDict struct {
	ID       string         `json:"id"`
	Code     sql.NullString `json:"code"`
	Name     sql.NullString `json:"name"`
	Remark   sql.NullString `json:"remark"`
	DictType sql.NullInt32  `json:"dict_type"`
	CreateAt sql.NullTime   `json:"create_at"`
	CreateBy sql.NullString `json:"create_by"`
	UpdateAt sql.NullTime   `json:"update_at"`
	UpdateBy sql.NullString `json:"update_by"`
}

type TCommDictItem struct {
	ID              string         `json:"id"`
	DictCode        sql.NullString `json:"dict_code"`
	ItemName        sql.NullString `json:"item_name"`
	ItemValue       string         `json:"item_value"`
	ItemOrder       sql.NullInt32  `json:"item_order"`
	ItemLevel       sql.NullInt32  `json:"item_level"`
	ParentItemValue sql.NullString `json:"parent_item_value"`
	CreateAt        sql.NullTime   `json:"create_at"`
	CreateBy        sql.NullString `json:"create_by"`
	UpdateAt        sql.NullTime   `json:"update_at"`
	UpdateBy        sql.NullString `json:"update_by"`
}

type TDashboard struct {
	ID        string         `json:"id"`
	Key       string         `json:"key"`
	Type      sql.NullInt32  `json:"type"`
	ProjectID sql.NullString `json:"project_id"`
	Setting   sql.NullString `json:"setting"`
	CreateAt  time.Time      `json:"create_at"`
	CreateBy  sql.NullString `json:"create_by"`
	UpdateAt  sql.NullTime   `json:"update_at"`
	UpdateBy  sql.NullString `json:"update_by"`
}

type TDept struct {
	ID           string         `json:"id"`
	ParentID     string         `json:"parent_id"`
	Name         sql.NullString `json:"name"`
	ShortName    string         `json:"short_name"`
	Code         sql.NullString `json:"code"`
	ManagerID    sql.NullString `json:"manager_id"`
	SortCode     sql.NullInt32  `json:"sort_code"`
	PropertyJson sql.NullString `json:"property_json"`
	Status       sql.NullString `json:"status"`
	Remark       sql.NullString `json:"remark"`
	IsDeleted    int16          `json:"is_deleted"`
	CreateAt     time.Time      `json:"create_at"`
	CreateBy     sql.NullString `json:"create_by"`
	UpdateAt     sql.NullTime   `json:"update_at"`
	UpdateBy     sql.NullString `json:"update_by"`
}

type TFile struct {
	ID            string         `json:"id"`
	OriginalName  sql.NullString `json:"original_name"`
	FileName      sql.NullString `json:"file_name"`
	FilePath      sql.NullString `json:"file_path"`
	ThumbFilePath sql.NullString `json:"thumb_file_path"`
	StorageType   sql.NullInt32  `json:"storage_type"`
	Shared        sql.NullInt32  `json:"shared"`
	IsDeleted     int16          `json:"is_deleted"`
	CreateAt      time.Time      `json:"create_at"`
	CreateBy      sql.NullString `json:"create_by"`
	UpdateAt      sql.NullTime   `json:"update_at"`
	UpdateBy      sql.NullString `json:"update_by"`
}

type TPosition struct {
	ID                 string         `json:"id"`
	Name               string         `json:"name"`
	Code               sql.NullString `json:"code"`
	IsVirtual          int16          `json:"is_virtual"`
	DataPermissionType sql.NullString `json:"data_permission_type"`
	PropertyJson       sql.NullString `json:"property_json"`
	IsDeleted          int16          `json:"is_deleted"`
	CreateAt           time.Time      `json:"create_at"`
	CreateBy           sql.NullString `json:"create_by"`
	UpdateAt           sql.NullTime   `json:"update_at"`
	UpdateBy           sql.NullString `json:"update_by"`
}

type TProject struct {
	ID        string         `json:"id"`
	ParentID  sql.NullString `json:"parent_id"`
	Name      sql.NullString `json:"name"`
	Survey    sql.NullString `json:"survey"`
	Setting   sql.NullString `json:"setting"`
	Status    sql.NullInt32  `json:"status"`
	Mode      sql.NullString `json:"mode"`
	Priority  sql.NullInt32  `json:"priority"`
	IsDeleted int16          `json:"is_deleted"`
	CreateAt  time.Time      `json:"create_at"`
	CreateBy  sql.NullString `json:"create_by"`
	UpdateAt  sql.NullTime   `json:"update_at"`
	UpdateBy  sql.NullString `json:"update_by"`
}

type TProjectPartner struct {
	ID             string         `json:"id"`
	Uid            sql.NullString `json:"uid"`
	ProjectID      sql.NullString `json:"project_id"`
	Type           sql.NullInt32  `json:"type"`
	Status         sql.NullInt32  `json:"status"`
	UserID         sql.NullString `json:"user_id"`
	UserName       sql.NullString `json:"user_name"`
	GroupID        sql.NullString `json:"group_id"`
	DataPermission sql.NullString `json:"data_permission"`
	InitialValue   sql.NullString `json:"initial_value"`
	CreateAt       time.Time      `json:"create_at"`
	CreateBy       sql.NullString `json:"create_by"`
	UpdateAt       sql.NullTime   `json:"update_at"`
	UpdateBy       sql.NullString `json:"update_by"`
}

type TRepo struct {
	ID          string         `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Category    sql.NullString `json:"category"`
	Mode        sql.NullString `json:"mode"`
	Shared      sql.NullInt16  `json:"shared"`
	Tag         sql.NullString `json:"tag"`
	Priority    sql.NullInt32  `json:"priority"`
	Setting     sql.NullString `json:"setting"`
	CreateAt    time.Time      `json:"create_at"`
	CreateBy    sql.NullString `json:"create_by"`
	UpdateAt    sql.NullTime   `json:"update_at"`
	UpdateBy    sql.NullString `json:"update_by"`
	IsPractice  sql.NullInt16  `json:"is_practice"`
}

type TRepoPartner struct {
	ID       string         `json:"id"`
	RepoID   sql.NullString `json:"repo_id"`
	UserID   sql.NullString `json:"user_id"`
	CreateAt time.Time      `json:"create_at"`
	CreateBy sql.NullString `json:"create_by"`
	UpdateAt sql.NullTime   `json:"update_at"`
	UpdateBy sql.NullString `json:"update_by"`
}

type TRepoTemplate struct {
	ID         string         `json:"id"`
	TemplateID sql.NullString `json:"template_id"`
	RepoID     sql.NullString `json:"repo_id"`
	CreateAt   time.Time      `json:"create_at"`
	CreateBy   sql.NullString `json:"create_by"`
}

type TRole struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Code      string         `json:"code"`
	Remark    sql.NullString `json:"remark"`
	Authority sql.NullString `json:"authority"`
	Status    sql.NullInt16  `json:"status"`
	IsDeleted int16          `json:"is_deleted"`
	CreateAt  time.Time      `json:"create_at"`
	CreateBy  sql.NullString `json:"create_by"`
	UpdateAt  sql.NullTime   `json:"update_at"`
	UpdateBy  sql.NullString `json:"update_by"`
}

type TSysInfo struct {
	ID           string         `json:"id"`
	Name         sql.NullString `json:"name"`
	Description  sql.NullString `json:"description"`
	Avatar       sql.NullString `json:"avatar"`
	Locale       sql.NullString `json:"locale"`
	Version      sql.NullString `json:"version"`
	Setting      sql.NullString `json:"setting"`
	AiSetting    sql.NullString `json:"ai_setting"`
	RegisterInfo sql.NullString `json:"register_info"`
	IsDefault    sql.NullInt16  `json:"is_default"`
	CreateAt     time.Time      `json:"create_at"`
	CreateBy     sql.NullString `json:"create_by"`
	UpdateAt     sql.NullTime   `json:"update_at"`
	UpdateBy     sql.NullString `json:"update_by"`
}

type TTag struct {
	ID       string         `json:"id"`
	EntityID sql.NullString `json:"entity_id"`
	Name     sql.NullString `json:"name"`
	Category sql.NullString `json:"category"`
	CreateAt time.Time      `json:"create_at"`
	CreateBy sql.NullString `json:"create_by"`
}

type TTemplate struct {
	ID           string         `json:"id"`
	RepoID       sql.NullString `json:"repo_id"`
	SerialNo     sql.NullString `json:"serial_no"`
	Name         sql.NullString `json:"name"`
	QuestionType sql.NullString `json:"question_type"`
	Template     sql.NullString `json:"template"`
	Mode         sql.NullString `json:"mode"`
	Category     sql.NullString `json:"category"`
	Tag          sql.NullString `json:"tag"`
	Priority     sql.NullInt32  `json:"priority"`
	PreviewUrl   sql.NullString `json:"preview_url"`
	Shared       sql.NullInt16  `json:"shared"`
	IsDeleted    int16          `json:"is_deleted"`
	CreateAt     time.Time      `json:"create_at"`
	CreateBy     sql.NullString `json:"create_by"`
	UpdateAt     sql.NullTime   `json:"update_at"`
	UpdateBy     sql.NullString `json:"update_by"`
}

type TUser struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	DeptID       sql.NullString `json:"dept_id"`
	Gender       sql.NullString `json:"gender"`
	Birthday     sql.NullTime   `json:"birthday"`
	Phone        sql.NullString `json:"phone"`
	Email        sql.NullString `json:"email"`
	Avatar       sql.NullString `json:"avatar"`
	Status       int16          `json:"status"`
	IsDeleted    int16          `json:"is_deleted"`
	CreateAt     time.Time      `json:"create_at"`
	CreateBy     sql.NullString `json:"create_by"`
	UpdateAt     sql.NullTime   `json:"update_at"`
	UpdateBy     sql.NullString `json:"update_by"`
	Profile      sql.NullString `json:"profile"`
	CorrectTimes sql.NullInt32  `json:"correct_times"`
}

type TUserBook struct {
	ID           string         `json:"id"`
	Name         sql.NullString `json:"name"`
	TemplateID   sql.NullString `json:"template_id"`
	WrongTimes   sql.NullInt32  `json:"wrong_times"`
	CorrectTimes sql.NullInt32  `json:"correct_times"`
	Note         sql.NullString `json:"note"`
	Status       sql.NullInt32  `json:"status"`
	Type         sql.NullInt32  `json:"type"`
	CreateAt     time.Time      `json:"create_at"`
	CreateBy     sql.NullString `json:"create_by"`
	UpdateAt     sql.NullTime   `json:"update_at"`
	UpdateBy     sql.NullString `json:"update_by"`
	RepoID       sql.NullString `json:"repo_id"`
	IsMarked     sql.NullInt16  `json:"is_marked"`
}

type TUserPosition struct {
	ID                string         `json:"id"`
	UserID            string         `json:"user_id"`
	DeptID            sql.NullString `json:"dept_id"`
	PositionID        sql.NullString `json:"position_id"`
	IsPrimaryPosition sql.NullInt16  `json:"is_primary_position"`
	PropertyJson      sql.NullString `json:"property_json"`
	CreateAt          time.Time      `json:"create_at"`
	CreateBy          sql.NullString `json:"create_by"`
	UpdateAt          sql.NullTime   `json:"update_at"`
	UpdateBy          sql.NullString `json:"update_by"`
}

type TUserRole struct {
	ID       string         `json:"id"`
	UserType string         `json:"user_type"`
	UserID   string         `json:"user_id"`
	RoleID   string         `json:"role_id"`
	CreateAt time.Time      `json:"create_at"`
	CreateBy sql.NullString `json:"create_by"`
	UpdateAt sql.NullTime   `json:"update_at"`
	UpdateBy sql.NullString `json:"update_by"`
}
