// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: overview.sql

package db

import (
	"context"
)

const userOverviewCounts = `-- name: UserOverviewCounts :one
SELECT
    (SELECT COUNT(*) FROM t_project   WHERE is_deleted = 0)            AS project_total,
    (SELECT COUNT(*) FROM t_project   WHERE is_deleted = 0 AND COALESCE(status, 0) = 1) AS project_published,
    (SELECT COUNT(*) FROM t_template  WHERE is_deleted = 0)            AS template_total,
    (SELECT COUNT(*) FROM t_repo)                                       AS repo_total,
    (SELECT COUNT(*) FROM t_answer    WHERE is_deleted = 0)            AS answer_total,
    (SELECT COUNT(*) FROM t_answer    WHERE is_deleted = 0 AND temp_save = 1) AS answer_finished,
    (SELECT COUNT(*) FROM t_user      WHERE is_deleted = 0)            AS user_total
`

type UserOverviewCountsRow struct {
	ProjectTotal     int64 `json:"project_total"`
	ProjectPublished int64 `json:"project_published"`
	TemplateTotal    int64 `json:"template_total"`
	RepoTotal        int64 `json:"repo_total"`
	AnswerTotal      int64 `json:"answer_total"`
	AnswerFinished   int64 `json:"answer_finished"`
	UserTotal        int64 `json:"user_total"`
}

// Powers /api/userOverview — top-level numbers the SK dashboard shows.
// One round-trip aggregate so the home screen renders fast.
func (q *Queries) UserOverviewCounts(ctx context.Context) (UserOverviewCountsRow, error) {
	row := q.db.QueryRowContext(ctx, userOverviewCounts)
	var i UserOverviewCountsRow
	err := row.Scan(
		&i.ProjectTotal,
		&i.ProjectPublished,
		&i.TemplateTotal,
		&i.RepoTotal,
		&i.AnswerTotal,
		&i.AnswerFinished,
		&i.UserTotal,
	)
	return i, err
}
