// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: partner.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countProjectPartners = `-- name: CountProjectPartners :one
SELECT COUNT(*) FROM t_project_partner
WHERE ($1::varchar IS NULL OR project_id = $1)
  AND ($2::text   IS NULL OR user_name ILIKE '%' || $2::text || '%')
`

type CountProjectPartnersParams struct {
	ProjectID sql.NullString `json:"project_id"`
	UserName  sql.NullString `json:"user_name"`
}

func (q *Queries) CountProjectPartners(ctx context.Context, arg CountProjectPartnersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectPartners, arg.ProjectID, arg.UserName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRepoPartners = `-- name: CountRepoPartners :one
SELECT COUNT(*) FROM t_repo_partner
WHERE ($1::varchar IS NULL OR repo_id = $1)
`

func (q *Queries) CountRepoPartners(ctx context.Context, repoID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRepoPartners, repoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProjectPartner = `-- name: CreateProjectPartner :exec
INSERT INTO t_project_partner (id, uid, project_id, type, status, user_id, user_name,
                                group_id, data_permission, initial_value, create_at, create_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), $11)
`

type CreateProjectPartnerParams struct {
	ID             string         `json:"id"`
	Uid            sql.NullString `json:"uid"`
	ProjectID      sql.NullString `json:"project_id"`
	Type           sql.NullInt32  `json:"type"`
	Status         sql.NullInt32  `json:"status"`
	UserID         sql.NullString `json:"user_id"`
	UserName       sql.NullString `json:"user_name"`
	GroupID        sql.NullString `json:"group_id"`
	DataPermission sql.NullString `json:"data_permission"`
	InitialValue   sql.NullString `json:"initial_value"`
	CreateBy       sql.NullString `json:"create_by"`
}

func (q *Queries) CreateProjectPartner(ctx context.Context, arg CreateProjectPartnerParams) error {
	_, err := q.db.ExecContext(ctx, createProjectPartner,
		arg.ID,
		arg.Uid,
		arg.ProjectID,
		arg.Type,
		arg.Status,
		arg.UserID,
		arg.UserName,
		arg.GroupID,
		arg.DataPermission,
		arg.InitialValue,
		arg.CreateBy,
	)
	return err
}

const createRepoPartner = `-- name: CreateRepoPartner :exec
INSERT INTO t_repo_partner (id, repo_id, user_id, create_at, create_by)
VALUES ($1, $2, $3, NOW(), $4)
`

type CreateRepoPartnerParams struct {
	ID       string         `json:"id"`
	RepoID   sql.NullString `json:"repo_id"`
	UserID   sql.NullString `json:"user_id"`
	CreateBy sql.NullString `json:"create_by"`
}

func (q *Queries) CreateRepoPartner(ctx context.Context, arg CreateRepoPartnerParams) error {
	_, err := q.db.ExecContext(ctx, createRepoPartner,
		arg.ID,
		arg.RepoID,
		arg.UserID,
		arg.CreateBy,
	)
	return err
}

const deleteProjectPartner = `-- name: DeleteProjectPartner :exec
DELETE FROM t_project_partner WHERE id = $1
`

func (q *Queries) DeleteProjectPartner(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectPartner, id)
	return err
}

const deleteRepoPartner = `-- name: DeleteRepoPartner :exec
DELETE FROM t_repo_partner WHERE id = $1
`

func (q *Queries) DeleteRepoPartner(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRepoPartner, id)
	return err
}

const listProjectPartners = `-- name: ListProjectPartners :many

SELECT id, uid, project_id, type, status, user_id, user_name, group_id,
       data_permission, initial_value, create_at, update_at, create_by
FROM t_project_partner
WHERE ($1::varchar IS NULL OR project_id = $1)
  AND ($2::text   IS NULL OR user_name ILIKE '%' || $2::text || '%')
ORDER BY create_at DESC
LIMIT $4 OFFSET $3
`

type ListProjectPartnersParams struct {
	ProjectID sql.NullString `json:"project_id"`
	UserName  sql.NullString `json:"user_name"`
	Off       int32          `json:"off"`
	Lim       int32          `json:"lim"`
}

type ListProjectPartnersRow struct {
	ID             string         `json:"id"`
	Uid            sql.NullString `json:"uid"`
	ProjectID      sql.NullString `json:"project_id"`
	Type           sql.NullInt32  `json:"type"`
	Status         sql.NullInt32  `json:"status"`
	UserID         sql.NullString `json:"user_id"`
	UserName       sql.NullString `json:"user_name"`
	GroupID        sql.NullString `json:"group_id"`
	DataPermission sql.NullString `json:"data_permission"`
	InitialValue   sql.NullString `json:"initial_value"`
	CreateAt       time.Time      `json:"create_at"`
	UpdateAt       sql.NullTime   `json:"update_at"`
	CreateBy       sql.NullString `json:"create_by"`
}

// ----- t_project_partner -----
func (q *Queries) ListProjectPartners(ctx context.Context, arg ListProjectPartnersParams) ([]ListProjectPartnersRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectPartners,
		arg.ProjectID,
		arg.UserName,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectPartnersRow{}
	for rows.Next() {
		var i ListProjectPartnersRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.ProjectID,
			&i.Type,
			&i.Status,
			&i.UserID,
			&i.UserName,
			&i.GroupID,
			&i.DataPermission,
			&i.InitialValue,
			&i.CreateAt,
			&i.UpdateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoPartners = `-- name: ListRepoPartners :many

SELECT id, repo_id, user_id, create_at, update_at, create_by
FROM t_repo_partner
WHERE ($1::varchar IS NULL OR repo_id = $1)
ORDER BY create_at DESC
LIMIT $3 OFFSET $2
`

type ListRepoPartnersParams struct {
	RepoID sql.NullString `json:"repo_id"`
	Off    int32          `json:"off"`
	Lim    int32          `json:"lim"`
}

type ListRepoPartnersRow struct {
	ID       string         `json:"id"`
	RepoID   sql.NullString `json:"repo_id"`
	UserID   sql.NullString `json:"user_id"`
	CreateAt time.Time      `json:"create_at"`
	UpdateAt sql.NullTime   `json:"update_at"`
	CreateBy sql.NullString `json:"create_by"`
}

// ----- t_repo_partner -----
func (q *Queries) ListRepoPartners(ctx context.Context, arg ListRepoPartnersParams) ([]ListRepoPartnersRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepoPartners, arg.RepoID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepoPartnersRow{}
	for rows.Next() {
		var i ListRepoPartnersRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.UserID,
			&i.CreateAt,
			&i.UpdateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
