// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: position.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countPositions = `-- name: CountPositions :one
SELECT COUNT(*) FROM t_position
WHERE is_deleted = 0
  AND ($1::text   IS NULL OR name ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountPositions(ctx context.Context, name sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPositions, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPosition = `-- name: CreatePosition :exec
INSERT INTO t_position (id, name, code, is_virtual, data_permission_type, property_json,
                        is_deleted, create_at, create_by)
VALUES ($1, $2, $3, $4, $5, $6, 0, NOW(), $7)
`

type CreatePositionParams struct {
	ID                 string         `json:"id"`
	Name               string         `json:"name"`
	Code               sql.NullString `json:"code"`
	IsVirtual          int16          `json:"is_virtual"`
	DataPermissionType sql.NullString `json:"data_permission_type"`
	PropertyJson       sql.NullString `json:"property_json"`
	CreateBy           sql.NullString `json:"create_by"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) error {
	_, err := q.db.ExecContext(ctx, createPosition,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.IsVirtual,
		arg.DataPermissionType,
		arg.PropertyJson,
		arg.CreateBy,
	)
	return err
}

const getPositionByID = `-- name: GetPositionByID :one
SELECT id, name, code, is_virtual, data_permission_type, property_json,
       create_at, update_at, create_by, update_by
FROM t_position WHERE id = $1 AND is_deleted = 0
`

type GetPositionByIDRow struct {
	ID                 string         `json:"id"`
	Name               string         `json:"name"`
	Code               sql.NullString `json:"code"`
	IsVirtual          int16          `json:"is_virtual"`
	DataPermissionType sql.NullString `json:"data_permission_type"`
	PropertyJson       sql.NullString `json:"property_json"`
	CreateAt           time.Time      `json:"create_at"`
	UpdateAt           sql.NullTime   `json:"update_at"`
	CreateBy           sql.NullString `json:"create_by"`
	UpdateBy           sql.NullString `json:"update_by"`
}

func (q *Queries) GetPositionByID(ctx context.Context, id string) (GetPositionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPositionByID, id)
	var i GetPositionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.IsVirtual,
		&i.DataPermissionType,
		&i.PropertyJson,
		&i.CreateAt,
		&i.UpdateAt,
		&i.CreateBy,
		&i.UpdateBy,
	)
	return i, err
}

const listPositions = `-- name: ListPositions :many
SELECT id, name, code, is_virtual, data_permission_type, property_json,
       create_at, update_at, create_by
FROM t_position
WHERE is_deleted = 0
  AND ($1::text   IS NULL OR name ILIKE '%' || $1::text || '%')
ORDER BY create_at DESC
LIMIT $3 OFFSET $2
`

type ListPositionsParams struct {
	Name sql.NullString `json:"name"`
	Off  int32          `json:"off"`
	Lim  int32          `json:"lim"`
}

type ListPositionsRow struct {
	ID                 string         `json:"id"`
	Name               string         `json:"name"`
	Code               sql.NullString `json:"code"`
	IsVirtual          int16          `json:"is_virtual"`
	DataPermissionType sql.NullString `json:"data_permission_type"`
	PropertyJson       sql.NullString `json:"property_json"`
	CreateAt           time.Time      `json:"create_at"`
	UpdateAt           sql.NullTime   `json:"update_at"`
	CreateBy           sql.NullString `json:"create_by"`
}

func (q *Queries) ListPositions(ctx context.Context, arg ListPositionsParams) ([]ListPositionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPositions, arg.Name, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPositionsRow{}
	for rows.Next() {
		var i ListPositionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.IsVirtual,
			&i.DataPermissionType,
			&i.PropertyJson,
			&i.CreateAt,
			&i.UpdateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePosition = `-- name: SoftDeletePosition :exec
UPDATE t_position SET is_deleted = 1, update_by = $1 WHERE id = $2 AND is_deleted = 0
`

type SoftDeletePositionParams struct {
	UpdateBy sql.NullString `json:"update_by"`
	ID       string         `json:"id"`
}

func (q *Queries) SoftDeletePosition(ctx context.Context, arg SoftDeletePositionParams) error {
	_, err := q.db.ExecContext(ctx, softDeletePosition, arg.UpdateBy, arg.ID)
	return err
}

const updatePosition = `-- name: UpdatePosition :exec
UPDATE t_position SET
    name                 = COALESCE($3,                 name),
    code                 = COALESCE($4,                 code),
    is_virtual           = COALESCE($5,           is_virtual),
    data_permission_type = COALESCE($6, data_permission_type),
    property_json        = COALESCE($7,        property_json),
    update_by            = $1
WHERE id = $2 AND is_deleted = 0
`

type UpdatePositionParams struct {
	UpdateBy           sql.NullString `json:"update_by"`
	ID                 string         `json:"id"`
	Name               sql.NullString `json:"name"`
	Code               sql.NullString `json:"code"`
	IsVirtual          sql.NullInt16  `json:"is_virtual"`
	DataPermissionType sql.NullString `json:"data_permission_type"`
	PropertyJson       sql.NullString `json:"property_json"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) error {
	_, err := q.db.ExecContext(ctx, updatePosition,
		arg.UpdateBy,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.IsVirtual,
		arg.DataPermissionType,
		arg.PropertyJson,
	)
	return err
}
