// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*)
FROM t_project
WHERE is_deleted = 0
  AND ($1::varchar IS NULL OR parent_id = $1)
  AND ($2::varchar      IS NULL OR mode      = $2)
  AND ($3::text         IS NULL OR name ILIKE '%' || $3::text || '%')
`

type CountProjectsParams struct {
	ParentID sql.NullString `json:"parent_id"`
	Mode     sql.NullString `json:"mode"`
	Name     sql.NullString `json:"name"`
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects, arg.ParentID, arg.Mode, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrashedProjects = `-- name: CountTrashedProjects :one
SELECT COUNT(*) FROM t_project WHERE is_deleted = 1
`

func (q *Queries) CountTrashedProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrashedProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO t_project (
    id, parent_id, name, survey, setting, status, mode, priority,
    is_deleted, create_at, create_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 0, NOW(), $9
)
`

type CreateProjectParams struct {
	ID       string         `json:"id"`
	ParentID sql.NullString `json:"parent_id"`
	Name     sql.NullString `json:"name"`
	Survey   sql.NullString `json:"survey"`
	Setting  sql.NullString `json:"setting"`
	Status   sql.NullInt32  `json:"status"`
	Mode     sql.NullString `json:"mode"`
	Priority sql.NullInt32  `json:"priority"`
	CreateBy sql.NullString `json:"create_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Survey,
		arg.Setting,
		arg.Status,
		arg.Mode,
		arg.Priority,
		arg.CreateBy,
	)
	return err
}

const distinctProjectModes = `-- name: DistinctProjectModes :many
SELECT DISTINCT mode FROM t_project
WHERE is_deleted = 0 AND mode IS NOT NULL AND mode <> ''
ORDER BY mode
`

func (q *Queries) DistinctProjectModes(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, distinctProjectModes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var mode sql.NullString
		if err := rows.Scan(&mode); err != nil {
			return nil, err
		}
		items = append(items, mode)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, parent_id, name, survey, setting, status, mode, priority,
       create_at, create_by, update_at, update_by
FROM t_project
WHERE id = $1 AND is_deleted = 0
`

type GetProjectByIDRow struct {
	ID       string         `json:"id"`
	ParentID sql.NullString `json:"parent_id"`
	Name     sql.NullString `json:"name"`
	Survey   sql.NullString `json:"survey"`
	Setting  sql.NullString `json:"setting"`
	Status   sql.NullInt32  `json:"status"`
	Mode     sql.NullString `json:"mode"`
	Priority sql.NullInt32  `json:"priority"`
	CreateAt time.Time      `json:"create_at"`
	CreateBy sql.NullString `json:"create_by"`
	UpdateAt sql.NullTime   `json:"update_at"`
	UpdateBy sql.NullString `json:"update_by"`
}

func (q *Queries) GetProjectByID(ctx context.Context, id string) (GetProjectByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Survey,
		&i.Setting,
		&i.Status,
		&i.Mode,
		&i.Priority,
		&i.CreateAt,
		&i.CreateBy,
		&i.UpdateAt,
		&i.UpdateBy,
	)
	return i, err
}

const hardDeleteProject = `-- name: HardDeleteProject :exec
DELETE FROM t_project WHERE id = $1
`

func (q *Queries) HardDeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteProject, id)
	return err
}

const listProjects = `-- name: ListProjects :many
SELECT id, parent_id, name, survey, setting, status, mode, priority,
       create_at, update_at, create_by
FROM t_project
WHERE is_deleted = 0
  AND ($1::varchar IS NULL OR parent_id = $1)
  AND ($2::varchar      IS NULL OR mode      = $2)
  AND ($3::text         IS NULL OR name ILIKE '%' || $3::text || '%')
ORDER BY priority ASC, create_at DESC
LIMIT $5 OFFSET $4
`

type ListProjectsParams struct {
	ParentID sql.NullString `json:"parent_id"`
	Mode     sql.NullString `json:"mode"`
	Name     sql.NullString `json:"name"`
	Off      int32          `json:"off"`
	Lim      int32          `json:"lim"`
}

type ListProjectsRow struct {
	ID       string         `json:"id"`
	ParentID sql.NullString `json:"parent_id"`
	Name     sql.NullString `json:"name"`
	Survey   sql.NullString `json:"survey"`
	Setting  sql.NullString `json:"setting"`
	Status   sql.NullInt32  `json:"status"`
	Mode     sql.NullString `json:"mode"`
	Priority sql.NullInt32  `json:"priority"`
	CreateAt time.Time      `json:"create_at"`
	UpdateAt sql.NullTime   `json:"update_at"`
	CreateBy sql.NullString `json:"create_by"`
}

// Optional filters: parent_id (exact), mode (exact), name (ILIKE).
// Pass NULL for any filter you don't want to apply.
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects,
		arg.ParentID,
		arg.Mode,
		arg.Name,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Survey,
			&i.Setting,
			&i.Status,
			&i.Mode,
			&i.Priority,
			&i.CreateAt,
			&i.UpdateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedProjects = `-- name: ListTrashedProjects :many
SELECT id, parent_id, name, status, mode, priority, create_at, update_at, create_by
FROM t_project
WHERE is_deleted = 1
ORDER BY update_at DESC NULLS LAST, create_at DESC
LIMIT $2 OFFSET $1
`

type ListTrashedProjectsParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

type ListTrashedProjectsRow struct {
	ID       string         `json:"id"`
	ParentID sql.NullString `json:"parent_id"`
	Name     sql.NullString `json:"name"`
	Status   sql.NullInt32  `json:"status"`
	Mode     sql.NullString `json:"mode"`
	Priority sql.NullInt32  `json:"priority"`
	CreateAt time.Time      `json:"create_at"`
	UpdateAt sql.NullTime   `json:"update_at"`
	CreateBy sql.NullString `json:"create_by"`
}

// C5 trash bin. Same shape as ListProjects but is_deleted = 1.
func (q *Queries) ListTrashedProjects(ctx context.Context, arg ListTrashedProjectsParams) ([]ListTrashedProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrashedProjects, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrashedProjectsRow{}
	for rows.Next() {
		var i ListTrashedProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Status,
			&i.Mode,
			&i.Priority,
			&i.CreateAt,
			&i.UpdateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProject = `-- name: RestoreProject :exec
UPDATE t_project SET is_deleted = 0, update_by = $1 WHERE id = $2 AND is_deleted = 1
`

type RestoreProjectParams struct {
	UpdateBy sql.NullString `json:"update_by"`
	ID       string         `json:"id"`
}

func (q *Queries) RestoreProject(ctx context.Context, arg RestoreProjectParams) error {
	_, err := q.db.ExecContext(ctx, restoreProject, arg.UpdateBy, arg.ID)
	return err
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE t_project SET is_deleted = 1, update_by = $1 WHERE id = $2 AND is_deleted = 0
`

type SoftDeleteProjectParams struct {
	UpdateBy sql.NullString `json:"update_by"`
	ID       string         `json:"id"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteProject, arg.UpdateBy, arg.ID)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE t_project SET
    parent_id = COALESCE($3,  parent_id),
    name      = COALESCE($4,       name),
    survey    = COALESCE($5,     survey),
    setting   = COALESCE($6,    setting),
    status    = COALESCE($7,     status),
    mode      = COALESCE($8,       mode),
    priority  = COALESCE($9,   priority),
    update_by = $1
WHERE id = $2 AND is_deleted = 0
`

type UpdateProjectParams struct {
	UpdateBy sql.NullString `json:"update_by"`
	ID       string         `json:"id"`
	ParentID sql.NullString `json:"parent_id"`
	Name     sql.NullString `json:"name"`
	Survey   sql.NullString `json:"survey"`
	Setting  sql.NullString `json:"setting"`
	Status   sql.NullInt32  `json:"status"`
	Mode     sql.NullString `json:"mode"`
	Priority sql.NullInt32  `json:"priority"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject,
		arg.UpdateBy,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Survey,
		arg.Setting,
		arg.Status,
		arg.Mode,
		arg.Priority,
	)
	return err
}
