// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM t_project WHERE is_deleted = 0
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, parent_id, name, status, mode, priority, create_at, update_at, create_by
FROM t_project
WHERE is_deleted = 0
ORDER BY priority ASC, create_at DESC
LIMIT $1 OFFSET $2
`

type ListProjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProjectsRow struct {
	ID       string         `json:"id"`
	ParentID sql.NullString `json:"parent_id"`
	Name     sql.NullString `json:"name"`
	Status   sql.NullInt32  `json:"status"`
	Mode     sql.NullString `json:"mode"`
	Priority sql.NullInt32  `json:"priority"`
	CreateAt time.Time      `json:"create_at"`
	UpdateAt sql.NullTime   `json:"update_at"`
	CreateBy sql.NullString `json:"create_by"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Status,
			&i.Mode,
			&i.Priority,
			&i.CreateAt,
			&i.UpdateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
