// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Cursor-style pagination for the xlsx export. The service loops over
	// (offset, limit) chunks so peak memory stays bounded even when the
	// project has tens of thousands of answers.
	AnswersForExportPage(ctx context.Context, arg AnswersForExportPageParams) ([]AnswersForExportPageRow, error)
	CountAnswersByProject(ctx context.Context, projectID string) (int64, error)
	CountDashboards(ctx context.Context) (int64, error)
	CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error)
	CountRepos(ctx context.Context) (int64, error)
	CountTemplates(ctx context.Context) (int64, error)
	CreateAnswer(ctx context.Context, arg CreateAnswerParams) error
	CreateFile(ctx context.Context, arg CreateFileParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) error
	CreateRepo(ctx context.Context, arg CreateRepoParams) error
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) error
	// t_repo has no is_deleted column in SK, so delete is hard.
	DeleteRepo(ctx context.Context, id string) error
	// Powers /api/template/listCategory. Returns each non-empty category
	// exactly once across the whole table (the previous heuristic walked
	// only the first 200 rows and missed values further in).
	DistinctTemplateCategories(ctx context.Context) ([]sql.NullString, error)
	// Returns the comma-separated tag column for every undeleted template;
	// the service splits and dedupes in Go because PG's string_to_array +
	// DISTINCT plumbing here doesn't add enough value to justify the
	// extra SQL.
	DistinctTemplateTagBlobs(ctx context.Context) ([]sql.NullString, error)
	// Fetch an active login record for password-style authentication.
	GetAccountByLogin(ctx context.Context, arg GetAccountByLoginParams) (GetAccountByLoginRow, error)
	GetAnswerByID(ctx context.Context, id string) (GetAnswerByIDRow, error)
	GetFileByID(ctx context.Context, id string) (GetFileByIDRow, error)
	// Look up a project partner by its short uid (the URL-token surrogate).
	// Used by the partner-token middleware to identify a participant
	// without forcing login.
	GetPartnerByUID(ctx context.Context, uid sql.NullString) (GetPartnerByUIDRow, error)
	GetProjectByID(ctx context.Context, id string) (GetProjectByIDRow, error)
	// Public survey-render query: returns only the data needed to render a
	// published, non-deleted survey to an unauthenticated visitor. Drafts
	// (status=0) and soft-deleted projects are invisible here.
	GetPublishedSurvey(ctx context.Context, id string) (GetPublishedSurveyRow, error)
	GetRepoByID(ctx context.Context, id string) (GetRepoByIDRow, error)
	GetTemplateByID(ctx context.Context, id string) (GetTemplateByIDRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	ListAnswersByProject(ctx context.Context, arg ListAnswersByProjectParams) ([]ListAnswersByProjectRow, error)
	ListDashboards(ctx context.Context, arg ListDashboardsParams) ([]ListDashboardsRow, error)
	// Projects in exam/exercise mode with at least one finished answer.
	// Drives /api/exercises for the user-facing exercise overview.
	ListExerciseProjects(ctx context.Context) ([]ListExerciseProjectsRow, error)
	// Optional filters: parent_id (exact), mode (exact), name (ILIKE).
	// Pass NULL for any filter you don't want to apply.
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	ListRepos(ctx context.Context, arg ListReposParams) ([]ListReposRow, error)
	// Returns the comma-separated authority strings for a user's roles.
	// Splitting/parsing happens in Go because SK stored authorities as a
	// single varchar(3000) blob per role.
	ListRoleAuthoritiesByUser(ctx context.Context, userID string) ([]ListRoleAuthoritiesByUserRow, error)
	// Return active role codes for a SysUser. Used to populate JWT claims
	// and (in P2+) to enforce permission gates.
	ListRoleCodesByUser(ctx context.Context, userID string) ([]string, error)
	ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]ListTemplatesRow, error)
	// Aggregated answer counters for a single project. PG's FILTER clause
	// avoids three separate COUNT queries.
	ProjectAnswerStats(ctx context.Context, projectID string) (ProjectAnswerStatsRow, error)
	SoftDeleteAnswer(ctx context.Context, arg SoftDeleteAnswerParams) error
	SoftDeleteFile(ctx context.Context, arg SoftDeleteFileParams) error
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) error
	SoftDeleteTemplate(ctx context.Context, arg SoftDeleteTemplateParams) error
	// Used by saveAnswer's resume flow: when the client returns a previously
	// issued answerId, we patch the existing draft instead of creating a
	// new row. Returns the number of rows touched so the service can fall
	// back to insert if the id is stale (deleted or never existed).
	UpdateAnswerInPlace(ctx context.Context, arg UpdateAnswerInPlaceParams) (int64, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) error
	UpdateRepo(ctx context.Context, arg UpdateRepoParams) error
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error
}

var _ Querier = (*Queries)(nil)
