// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountDashboards(ctx context.Context) (int64, error)
	CountProjects(ctx context.Context) (int64, error)
	CountRepos(ctx context.Context) (int64, error)
	CountTemplates(ctx context.Context) (int64, error)
	// Fetch an active login record for password-style authentication.
	GetAccountByLogin(ctx context.Context, arg GetAccountByLoginParams) (GetAccountByLoginRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	ListDashboards(ctx context.Context, arg ListDashboardsParams) ([]ListDashboardsRow, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	ListRepos(ctx context.Context, arg ListReposParams) ([]ListReposRow, error)
	// Returns the comma-separated authority strings for a user's roles.
	// Splitting/parsing happens in Go because SK stored authorities as a
	// single varchar(3000) blob per role.
	ListRoleAuthoritiesByUser(ctx context.Context, userID string) ([]ListRoleAuthoritiesByUserRow, error)
	// Return active role codes for a SysUser. Used to populate JWT claims
	// and (in P2+) to enforce permission gates.
	ListRoleCodesByUser(ctx context.Context, userID string) ([]string, error)
	ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]ListTemplatesRow, error)
}

var _ Querier = (*Queries)(nil)
