// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repo.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countRepos = `-- name: CountRepos :one
SELECT COUNT(*) FROM t_repo
`

func (q *Queries) CountRepos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRepos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRepos = `-- name: ListRepos :many
SELECT id, name, description, category, mode, shared, tag, priority, is_practice,
       create_at, update_at, create_by
FROM t_repo
ORDER BY COALESCE(priority, 1000) ASC, create_at DESC
LIMIT $1 OFFSET $2
`

type ListReposParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListReposRow struct {
	ID          string         `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Category    sql.NullString `json:"category"`
	Mode        sql.NullString `json:"mode"`
	Shared      sql.NullInt16  `json:"shared"`
	Tag         sql.NullString `json:"tag"`
	Priority    sql.NullInt32  `json:"priority"`
	IsPractice  sql.NullInt16  `json:"is_practice"`
	CreateAt    time.Time      `json:"create_at"`
	UpdateAt    sql.NullTime   `json:"update_at"`
	CreateBy    sql.NullString `json:"create_by"`
}

func (q *Queries) ListRepos(ctx context.Context, arg ListReposParams) ([]ListReposRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReposRow{}
	for rows.Next() {
		var i ListReposRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Mode,
			&i.Shared,
			&i.Tag,
			&i.Priority,
			&i.IsPractice,
			&i.CreateAt,
			&i.UpdateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
