// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const answersForExportPage = `-- name: AnswersForExportPage :many
SELECT id, project_id, answer, attachment, meta_info, temp_save,
       exam_info, exam_exercise_type, exam_score,
       create_at, create_by
FROM t_answer
WHERE project_id = $1 AND is_deleted = 0
ORDER BY create_at ASC
LIMIT $2 OFFSET $3
`

type AnswersForExportPageParams struct {
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type AnswersForExportPageRow struct {
	ID               string          `json:"id"`
	ProjectID        string          `json:"project_id"`
	Answer           sql.NullString  `json:"answer"`
	Attachment       sql.NullString  `json:"attachment"`
	MetaInfo         sql.NullString  `json:"meta_info"`
	TempSave         sql.NullInt32   `json:"temp_save"`
	ExamInfo         sql.NullString  `json:"exam_info"`
	ExamExerciseType sql.NullString  `json:"exam_exercise_type"`
	ExamScore        sql.NullFloat64 `json:"exam_score"`
	CreateAt         time.Time       `json:"create_at"`
	CreateBy         sql.NullString  `json:"create_by"`
}

// Cursor-style pagination for the xlsx export. The service loops over
// (offset, limit) chunks so peak memory stays bounded even when the
// project has tens of thousands of answers.
func (q *Queries) AnswersForExportPage(ctx context.Context, arg AnswersForExportPageParams) ([]AnswersForExportPageRow, error) {
	rows, err := q.db.QueryContext(ctx, answersForExportPage, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnswersForExportPageRow{}
	for rows.Next() {
		var i AnswersForExportPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Answer,
			&i.Attachment,
			&i.MetaInfo,
			&i.TempSave,
			&i.ExamInfo,
			&i.ExamExerciseType,
			&i.ExamScore,
			&i.CreateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseProjects = `-- name: ListExerciseProjects :many
SELECT
    p.id,
    p.name,
    p.mode,
    COUNT(a.id)                                       AS answer_count,
    COUNT(a.id) FILTER (WHERE a.temp_save = 1)         AS finished_count,
    COALESCE(AVG(a.exam_score), 0)::double precision   AS avg_score
FROM t_project p
LEFT JOIN t_answer a
       ON a.project_id = p.id AND a.is_deleted = 0
WHERE p.is_deleted = 0
  AND p.mode IN ('exam', 'exercise')
  AND COALESCE(p.status, 0) = 1
GROUP BY p.id, p.name, p.mode
ORDER BY p.create_at DESC
`

type ListExerciseProjectsRow struct {
	ID            string         `json:"id"`
	Name          sql.NullString `json:"name"`
	Mode          sql.NullString `json:"mode"`
	AnswerCount   int64          `json:"answer_count"`
	FinishedCount int64          `json:"finished_count"`
	AvgScore      float64        `json:"avg_score"`
}

// Projects in exam/exercise mode with at least one finished answer.
// Drives /api/exercises for the user-facing exercise overview.
func (q *Queries) ListExerciseProjects(ctx context.Context) ([]ListExerciseProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExerciseProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExerciseProjectsRow{}
	for rows.Next() {
		var i ListExerciseProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mode,
			&i.AnswerCount,
			&i.FinishedCount,
			&i.AvgScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectAnswerStats = `-- name: ProjectAnswerStats :one
SELECT
    COUNT(*)                                  AS total,
    COUNT(*) FILTER (WHERE temp_save = 1)     AS finished,
    COUNT(*) FILTER (WHERE temp_save = 0)     AS draft,
    COALESCE(AVG(exam_score), 0)::double precision AS avg_score
FROM t_answer
WHERE project_id = $1 AND is_deleted = 0
`

type ProjectAnswerStatsRow struct {
	Total    int64   `json:"total"`
	Finished int64   `json:"finished"`
	Draft    int64   `json:"draft"`
	AvgScore float64 `json:"avg_score"`
}

// Aggregated answer counters for a single project. PG's FILTER clause
// avoids three separate COUNT queries.
func (q *Queries) ProjectAnswerStats(ctx context.Context, projectID string) (ProjectAnswerStatsRow, error) {
	row := q.db.QueryRowContext(ctx, projectAnswerStats, projectID)
	var i ProjectAnswerStatsRow
	err := row.Scan(
		&i.Total,
		&i.Finished,
		&i.Draft,
		&i.AvgScore,
	)
	return i, err
}
