// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package db

import (
	"context"
)

const listRoleAuthoritiesByUser = `-- name: ListRoleAuthoritiesByUser :many
SELECT r.code, COALESCE(r.authority, '') AS authority
FROM t_user_role ur
JOIN t_role r ON r.id = ur.role_id
WHERE ur.user_id = $1
  AND ur.user_type = 'SysUser'
  AND r.is_deleted = 0
  AND r.status = 1
`

type ListRoleAuthoritiesByUserRow struct {
	Code      string `json:"code"`
	Authority string `json:"authority"`
}

// Returns the comma-separated authority strings for a user's roles.
// Splitting/parsing happens in Go because SK stored authorities as a
// single varchar(3000) blob per role.
func (q *Queries) ListRoleAuthoritiesByUser(ctx context.Context, userID string) ([]ListRoleAuthoritiesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoleAuthoritiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleAuthoritiesByUserRow{}
	for rows.Next() {
		var i ListRoleAuthoritiesByUserRow
		if err := rows.Scan(&i.Code, &i.Authority); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleCodesByUser = `-- name: ListRoleCodesByUser :many
SELECT r.code
FROM t_user_role ur
JOIN t_role r ON r.id = ur.role_id
WHERE ur.user_id = $1
  AND ur.user_type = 'SysUser'
  AND r.is_deleted = 0
  AND r.status = 1
ORDER BY r.code
`

// Return active role codes for a SysUser. Used to populate JWT claims
// and (in P2+) to enforce permission gates.
func (q *Queries) ListRoleCodesByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRoleCodesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
