// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: survey.sql

package db

import (
	"context"
	"database/sql"
)

const getPartnerByUID = `-- name: GetPartnerByUID :one
SELECT id, project_id, type, status, user_id, user_name, group_id
FROM t_project_partner
WHERE uid = $1
LIMIT 1
`

type GetPartnerByUIDRow struct {
	ID        string         `json:"id"`
	ProjectID sql.NullString `json:"project_id"`
	Type      sql.NullInt32  `json:"type"`
	Status    sql.NullInt32  `json:"status"`
	UserID    sql.NullString `json:"user_id"`
	UserName  sql.NullString `json:"user_name"`
	GroupID   sql.NullString `json:"group_id"`
}

// Look up a project partner by its short uid (the URL-token surrogate).
// Used by the partner-token middleware to identify a participant
// without forcing login.
func (q *Queries) GetPartnerByUID(ctx context.Context, uid sql.NullString) (GetPartnerByUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPartnerByUID, uid)
	var i GetPartnerByUIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Status,
		&i.UserID,
		&i.UserName,
		&i.GroupID,
	)
	return i, err
}

const getPublishedSurvey = `-- name: GetPublishedSurvey :one
SELECT id, name, survey, setting, mode, status
FROM t_project
WHERE id = $1 AND is_deleted = 0 AND COALESCE(status, 0) = 1
`

type GetPublishedSurveyRow struct {
	ID      string         `json:"id"`
	Name    sql.NullString `json:"name"`
	Survey  sql.NullString `json:"survey"`
	Setting sql.NullString `json:"setting"`
	Mode    sql.NullString `json:"mode"`
	Status  sql.NullInt32  `json:"status"`
}

// Public survey-render query: returns only the data needed to render a
// published, non-deleted survey to an unauthenticated visitor. Drafts
// (status=0) and soft-deleted projects are invisible here.
func (q *Queries) GetPublishedSurvey(ctx context.Context, id string) (GetPublishedSurveyRow, error) {
	row := q.db.QueryRowContext(ctx, getPublishedSurvey, id)
	var i GetPublishedSurveyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Survey,
		&i.Setting,
		&i.Mode,
		&i.Status,
	)
	return i, err
}
