// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sysinfo.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getDefaultSysInfo = `-- name: GetDefaultSysInfo :one
SELECT id, name, description, avatar, locale, version,
       setting, ai_setting, register_info, is_default,
       create_at, update_at, create_by, update_by
FROM t_sys_info
ORDER BY (is_default = 1) DESC, create_at ASC
LIMIT 1
`

type GetDefaultSysInfoRow struct {
	ID           string         `json:"id"`
	Name         sql.NullString `json:"name"`
	Description  sql.NullString `json:"description"`
	Avatar       sql.NullString `json:"avatar"`
	Locale       sql.NullString `json:"locale"`
	Version      sql.NullString `json:"version"`
	Setting      sql.NullString `json:"setting"`
	AiSetting    sql.NullString `json:"ai_setting"`
	RegisterInfo sql.NullString `json:"register_info"`
	IsDefault    sql.NullInt16  `json:"is_default"`
	CreateAt     time.Time      `json:"create_at"`
	UpdateAt     sql.NullTime   `json:"update_at"`
	CreateBy     sql.NullString `json:"create_by"`
	UpdateBy     sql.NullString `json:"update_by"`
}

// Returns the singleton system-info row. SK seeded id='1'; we tolerate
// any id but prefer the row marked is_default=1.
func (q *Queries) GetDefaultSysInfo(ctx context.Context) (GetDefaultSysInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getDefaultSysInfo)
	var i GetDefaultSysInfoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Avatar,
		&i.Locale,
		&i.Version,
		&i.Setting,
		&i.AiSetting,
		&i.RegisterInfo,
		&i.IsDefault,
		&i.CreateAt,
		&i.UpdateAt,
		&i.CreateBy,
		&i.UpdateBy,
	)
	return i, err
}

const updateDefaultSysInfo = `-- name: UpdateDefaultSysInfo :exec
UPDATE t_sys_info SET
    name          = COALESCE($3,          name),
    description   = COALESCE($4,   description),
    avatar        = COALESCE($5,        avatar),
    locale        = COALESCE($6,        locale),
    version       = COALESCE($7,       version),
    setting       = COALESCE($8,       setting),
    ai_setting    = COALESCE($9,    ai_setting),
    register_info = COALESCE($10, register_info),
    update_by     = $1
WHERE id = $2
`

type UpdateDefaultSysInfoParams struct {
	UpdateBy     sql.NullString `json:"update_by"`
	ID           string         `json:"id"`
	Name         sql.NullString `json:"name"`
	Description  sql.NullString `json:"description"`
	Avatar       sql.NullString `json:"avatar"`
	Locale       sql.NullString `json:"locale"`
	Version      sql.NullString `json:"version"`
	Setting      sql.NullString `json:"setting"`
	AiSetting    sql.NullString `json:"ai_setting"`
	RegisterInfo sql.NullString `json:"register_info"`
}

func (q *Queries) UpdateDefaultSysInfo(ctx context.Context, arg UpdateDefaultSysInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateDefaultSysInfo,
		arg.UpdateBy,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Avatar,
		arg.Locale,
		arg.Version,
		arg.Setting,
		arg.AiSetting,
		arg.RegisterInfo,
	)
	return err
}
