// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: template.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countTemplates = `-- name: CountTemplates :one
SELECT COUNT(*) FROM t_template WHERE is_deleted = 0
`

func (q *Queries) CountTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, repo_id, serial_no, name, question_type, mode, category, tag,
       priority, preview_url, shared, create_at, update_at, create_by
FROM t_template
WHERE is_deleted = 0
ORDER BY COALESCE(priority, 1000) ASC, create_at DESC
LIMIT $1 OFFSET $2
`

type ListTemplatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTemplatesRow struct {
	ID           string         `json:"id"`
	RepoID       sql.NullString `json:"repo_id"`
	SerialNo     sql.NullString `json:"serial_no"`
	Name         sql.NullString `json:"name"`
	QuestionType sql.NullString `json:"question_type"`
	Mode         sql.NullString `json:"mode"`
	Category     sql.NullString `json:"category"`
	Tag          sql.NullString `json:"tag"`
	Priority     sql.NullInt32  `json:"priority"`
	PreviewUrl   sql.NullString `json:"preview_url"`
	Shared       sql.NullInt16  `json:"shared"`
	CreateAt     time.Time      `json:"create_at"`
	UpdateAt     sql.NullTime   `json:"update_at"`
	CreateBy     sql.NullString `json:"create_by"`
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]ListTemplatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplatesRow{}
	for rows.Next() {
		var i ListTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.SerialNo,
			&i.Name,
			&i.QuestionType,
			&i.Mode,
			&i.Category,
			&i.Tag,
			&i.Priority,
			&i.PreviewUrl,
			&i.Shared,
			&i.CreateAt,
			&i.UpdateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
