// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, dept_id, gender, email, avatar, status, profile
FROM t_user
WHERE id = $1
  AND is_deleted = 0
`

type GetUserByIDRow struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	DeptID  sql.NullString `json:"dept_id"`
	Gender  sql.NullString `json:"gender"`
	Email   sql.NullString `json:"email"`
	Avatar  sql.NullString `json:"avatar"`
	Status  int16          `json:"status"`
	Profile sql.NullString `json:"profile"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeptID,
		&i.Gender,
		&i.Email,
		&i.Avatar,
		&i.Status,
		&i.Profile,
	)
	return i, err
}
