// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: userbook.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countUserBooks = `-- name: CountUserBooks :one
SELECT COUNT(*) FROM t_user_book
WHERE ($1::varchar IS NULL OR create_by = $1)
  AND ($2::varchar   IS NULL OR repo_id   = $2)
  AND ($3::int          IS NULL OR type      = $3)
`

type CountUserBooksParams struct {
	CreateBy sql.NullString `json:"create_by"`
	RepoID   sql.NullString `json:"repo_id"`
	Type     sql.NullInt32  `json:"type"`
}

func (q *Queries) CountUserBooks(ctx context.Context, arg CountUserBooksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserBooks, arg.CreateBy, arg.RepoID, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserBook = `-- name: CreateUserBook :exec
INSERT INTO t_user_book (id, name, template_id, wrong_times, correct_times, note,
                         status, type, repo_id, is_marked, create_at, create_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), $11)
`

type CreateUserBookParams struct {
	ID           string         `json:"id"`
	Name         sql.NullString `json:"name"`
	TemplateID   sql.NullString `json:"template_id"`
	WrongTimes   sql.NullInt32  `json:"wrong_times"`
	CorrectTimes sql.NullInt32  `json:"correct_times"`
	Note         sql.NullString `json:"note"`
	Status       sql.NullInt32  `json:"status"`
	Type         sql.NullInt32  `json:"type"`
	RepoID       sql.NullString `json:"repo_id"`
	IsMarked     sql.NullInt16  `json:"is_marked"`
	CreateBy     sql.NullString `json:"create_by"`
}

func (q *Queries) CreateUserBook(ctx context.Context, arg CreateUserBookParams) error {
	_, err := q.db.ExecContext(ctx, createUserBook,
		arg.ID,
		arg.Name,
		arg.TemplateID,
		arg.WrongTimes,
		arg.CorrectTimes,
		arg.Note,
		arg.Status,
		arg.Type,
		arg.RepoID,
		arg.IsMarked,
		arg.CreateBy,
	)
	return err
}

const deleteUserBook = `-- name: DeleteUserBook :exec
DELETE FROM t_user_book WHERE id = $1
`

func (q *Queries) DeleteUserBook(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUserBook, id)
	return err
}

const listUserBooks = `-- name: ListUserBooks :many

SELECT id, name, template_id, wrong_times, correct_times, note, status, type,
       repo_id, is_marked, create_at, update_at, create_by
FROM t_user_book
WHERE ($1::varchar IS NULL OR create_by = $1)
  AND ($2::varchar   IS NULL OR repo_id   = $2)
  AND ($3::int          IS NULL OR type      = $3)
ORDER BY create_at DESC
LIMIT $5 OFFSET $4
`

type ListUserBooksParams struct {
	CreateBy sql.NullString `json:"create_by"`
	RepoID   sql.NullString `json:"repo_id"`
	Type     sql.NullInt32  `json:"type"`
	Off      int32          `json:"off"`
	Lim      int32          `json:"lim"`
}

type ListUserBooksRow struct {
	ID           string         `json:"id"`
	Name         sql.NullString `json:"name"`
	TemplateID   sql.NullString `json:"template_id"`
	WrongTimes   sql.NullInt32  `json:"wrong_times"`
	CorrectTimes sql.NullInt32  `json:"correct_times"`
	Note         sql.NullString `json:"note"`
	Status       sql.NullInt32  `json:"status"`
	Type         sql.NullInt32  `json:"type"`
	RepoID       sql.NullString `json:"repo_id"`
	IsMarked     sql.NullInt16  `json:"is_marked"`
	CreateAt     time.Time      `json:"create_at"`
	UpdateAt     sql.NullTime   `json:"update_at"`
	CreateBy     sql.NullString `json:"create_by"`
}

// ----- t_user_book (a.k.a. wrong-question book / favourites) -----
// The book is per (create_by, type) where type=1 is wrong questions
// and type=2 is favourites. Filter by repo_id when the UI is showing
// a single repo's pool.
func (q *Queries) ListUserBooks(ctx context.Context, arg ListUserBooksParams) ([]ListUserBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserBooks,
		arg.CreateBy,
		arg.RepoID,
		arg.Type,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserBooksRow{}
	for rows.Next() {
		var i ListUserBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TemplateID,
			&i.WrongTimes,
			&i.CorrectTimes,
			&i.Note,
			&i.Status,
			&i.Type,
			&i.RepoID,
			&i.IsMarked,
			&i.CreateAt,
			&i.UpdateAt,
			&i.CreateBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserBook = `-- name: UpdateUserBook :exec
UPDATE t_user_book SET
    name          = COALESCE($3,          name),
    template_id   = COALESCE($4,   template_id),
    wrong_times   = COALESCE($5,   wrong_times),
    correct_times = COALESCE($6, correct_times),
    note          = COALESCE($7,          note),
    status        = COALESCE($8,        status),
    type          = COALESCE($9,          type),
    repo_id       = COALESCE($10,       repo_id),
    is_marked     = COALESCE($11,     is_marked),
    update_by     = $1
WHERE id = $2
`

type UpdateUserBookParams struct {
	UpdateBy     sql.NullString `json:"update_by"`
	ID           string         `json:"id"`
	Name         sql.NullString `json:"name"`
	TemplateID   sql.NullString `json:"template_id"`
	WrongTimes   sql.NullInt32  `json:"wrong_times"`
	CorrectTimes sql.NullInt32  `json:"correct_times"`
	Note         sql.NullString `json:"note"`
	Status       sql.NullInt32  `json:"status"`
	Type         sql.NullInt32  `json:"type"`
	RepoID       sql.NullString `json:"repo_id"`
	IsMarked     sql.NullInt16  `json:"is_marked"`
}

func (q *Queries) UpdateUserBook(ctx context.Context, arg UpdateUserBookParams) error {
	_, err := q.db.ExecContext(ctx, updateUserBook,
		arg.UpdateBy,
		arg.ID,
		arg.Name,
		arg.TemplateID,
		arg.WrongTimes,
		arg.CorrectTimes,
		arg.Note,
		arg.Status,
		arg.Type,
		arg.RepoID,
		arg.IsMarked,
	)
	return err
}
